ekf_filter_node:
  ros__parameters:
    
    use_sim_time: true 
    
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    transform_timeout: 0.1

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Wheel Odometry 
    odom0: /localisation
    # X, Y, Z, Roll, Pitch, Yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az
    odom0_config: [true,  true,  false,  #X and Y position
                   false, false, true,   #Yaw (rotation)
                   true,  false, false,  #Forward Speed (Vx)
                   false, false, true,   #Turn Speed (Vyaw)
                   false, false, false]
    
    # Webots IMU (Accelerometer) 
    imu0: /imu/data
    # X, Y, Z, Roll, Pitch, Yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  false]   # X and Y Acceleration
                  
    
    imu0_remove_gravitational_acceleration: true