ekf_filter_node:
  ros__parameters:
    
    use_sim_time: true 
    
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    transform_timeout: 0.1

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Wheel Odometry 
    odom0: /localisation
    # X, Y, Z, Roll, Pitch, Yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az
    odom0_config: [true,  true,  false,  # We want X and Y position
                   false, false, true,   # We want Yaw (rotation)
                   true,  false, false,  # We want Forward Speed (Vx)
                   false, false, true,   # We want Turn Speed (Vyaw)
                   false, false, false]
    
    # Webots IMU (Accelerometer) 
    imu0: /imu/data
    # X, Y, Z, Roll, Pitch, Yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  false]   # We ONLY want X and Y Acceleration
                  
    # Ignores Z-axis gravity pull so the car doesn't think it's flying
    imu0_remove_gravitational_acceleration: true